### ISSUE TITLE
Handle Events Calendar (fullcalendar.io)

### ISSUE THREAD

**Issue by BogiThomsen** [Minibrams/Rusperiode#15]
- [x] Create Migration for planner in event
- [x] Add SCSS classes for different planners
- [x] Change time to 24h
- [x] Add filtering calendar form different planners

**Comment by frederikspang** [comment]
https://stackoverflow.com/questions/6641355/jquery-fullcalendar-event-filtering

**Comment by BogiThomsen** [comment]
Add Planner to event in db
Use this to add different colors to events from different Planners(Prosa/Ida/S'et/Os)
Add toggle to filter calendar, so it only shows events from one Planner.

**Comment by BogiThomsen** [comment]
Format time in calendar as 24h

**Comment by BogiThomsen** [comment]
add drop down in admin/menu for choosing between allowed planners

**Comment by BogiThomsen** [comment]
Add dropdown in admin panel flyttes til engang når spang kigger på permissions and shit... umiddelbar research siger at det kan man ikke, medmindre vi smider accepted planners ind i databasen og laver det som en relation.. hvilket er grimt

**Comment by BogiThomsen** [comment]
Dropdown i admin pannel blev fixed i #19, dog er det hardcodet. Mangler løsning på at "ruskorps" er forskellige farver alt efter fakultet.
